# Generated by Django 2.2.6 on 2019-11-17 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_auto_20191117_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseitem',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_item', to='shop.Product'),
        ),
    ]
