# Generated by Django 2.2.6 on 2019-11-08 16:26

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=django_fsm.FSMField(choices=[('Draft', 'draft'), ('Published', 'published')], default='draft', max_length=50, protected=True),
        ),
    ]
