# Generated by Django 2.2.6 on 2019-11-11 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chore', '0001_initial'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rental_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='chore.RentalPeriod'),
        ),
    ]
