# Generated by Django 2.2.6 on 2019-11-08 16:29

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=django_fsm.FSMField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=50, protected=True),
        ),
    ]
