on: [push]
jobs:
  pre-check:
    name: Pre check
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: Install Requirements
        run: |
          pip3 install -r dev-requirements.txt
      - name: Run linter
        run: |
          flake8 .
  test-backend:
    name: Test backend
    runs-on: ubuntu-18.04
    env:
      TAG: 0.1.${{ github.sha }}
    needs: pre-check
    steps:
      - uses: actions/checkout@v1
      - name: set env
        run: |
          echo -e "SECRET_KEY=xxx\nDB_NAME=rental\nDB_USER=rental\nDB_PASS=rental" >> .env
      - name: build backend
        run: |
          docker build -t docker.pkg.github.com/godesteem/rental/backend:${TAG} .
      - name: run tests
        run: |
          docker-compose -f docker-compose.test.yml up -d

  push-container:
    name: Push Container
    runs-on: ubuntu-18.04
    env:
      TAG: 0.1.${{ github.sha }}
    needs: test-backend
    steps:
      - uses: actions/checkout@v1
      - name: push
        run: |
          docker login docker.pkg.github.com --username philsupertramp -p ${secrets.GITHUB_TOKEN}
          docker push docker.pkg.github.com/godesteem/rental/backend:${TAG}