on: [push]
jobs:
  pre-check:
    name: Pre ceck
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7' # Version range or exact version of a Python version to use, using semvers version range syntax.
      - name: Install Requirements
        run: |
          pip3 install -r dev-requirements.txt
      - name: Run linter
        run: |
          flake8 .
  test-backend:
    name: Test backend
    runs-on: ubuntu-18.04
    env:
      TAG: 0.1.${{ github.sha }}
    needs: pre-check
    steps:
      - uses: actions/checkout@v1
      - name: set env
        run: |
          echo -e "SECRET_KEY=xxx\nDB_NAME=rental\nDB_USER=rental\nDB_PASS=rental" >> .env
      - name: build backend
        run: |
          docker build -t rental .
      - name: run tests
        run: |
          docker-compose -f docker-compose.test.yml up -d
