on: [push]
jobs:
  test-backend:
    name: Test backend
    runs-on: ubuntu-18.04
    env:
      TAG: 0.1.${{ github.sha }}
    steps:
      - uses: actions/checkout@v1
      - name: build and test backend
        run: |
          docker build -t rental:$TAG .
          docker run rental:$TAG python manage.py test -v 2